# Generated by Django 4.2.3 on 2023-07-22 19:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_images/', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('link', models.URLField(max_length=2048, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlər',
            },
        ),
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Ad')),
                ('website', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Vebsayt')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Ünvan')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ContactInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('contact_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='Əlaqə nömrəsi')),
            ],
            options={
                'verbose_name': 'Əlaqə məlumatı',
                'verbose_name_plural': 'Əlaqə məlumatları',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('subject', models.CharField(max_length=256, verbose_name='Mövzu')),
                ('message', models.TextField(verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Şəkil')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='Tarix')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
            ],
            options={
                'verbose_name': 'Xəbər',
                'verbose_name_plural': 'Xəbərlər',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OnlineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('school', models.CharField(max_length=528, verbose_name='Təhsil aldığı məktəb')),
                ('university', models.CharField(max_length=528, verbose_name='Bitirdiyi universitet')),
                ('speciality', models.CharField(max_length=528, verbose_name='İxtisas')),
                ('identity_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi')),
                ('point', models.CharField(max_length=100, verbose_name='Qəbul balı')),
            ],
            options={
                'verbose_name': 'Kursa onlayn qeydiyyat',
                'verbose_name_plural': 'Kursa onlayn qeydiyyatlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PhotoGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=528, verbose_name='Başlıq')),
                ('image', models.ImageField(upload_to='photo_gallery_images/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Foto Qalereya',
                'verbose_name_plural': 'Foto Qalereyalar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=528, verbose_name='Müraciət edilən vakansiyanın adı')),
                ('full_name', models.CharField(max_length=528, verbose_name='Soyad, ad, ata adı')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('birthdate', models.CharField(max_length=256, verbose_name='Doğum tarixi')),
                ('subject', models.CharField(max_length=528, verbose_name='Tədris etmək istənilən fənn')),
                ('home_phone', models.CharField(max_length=50, verbose_name='Ev telefon nömrəsi')),
                ('mobile_phone', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('address', models.CharField(max_length=528, verbose_name='Ünvan')),
                ('company_name1', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Şirkətin adı, ünvanı və fəaliyyət göstərdiyi sahə 1')),
                ('duty1', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Vəzifə və əsas öhdəliklər 1')),
                ('leaving_reason1', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Tərk etmə səbəbi 1')),
                ('company_name2', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Şirkətin adı, ünvanı və fəaliyyət göstərdiyi sahə 2')),
                ('duty2', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Vəzifə və əsas öhdəliklər 2')),
                ('leaving_reason2', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Tərk etmə səbəbi 2')),
                ('company_name3', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Şirkətin adı, ünvanı və fəaliyyət göstərdiyi sahə 3')),
                ('duty3', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Vəzifə və əsas öhdəliklər 3')),
                ('leaving_reason3', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Tərk etmə səbəbi 3')),
                ('university1', models.CharField(blank=True, max_length=528, null=True, verbose_name='Universitet 1')),
                ('speciality1', models.CharField(blank=True, max_length=528, null=True, verbose_name='İxtisas və dərəcə 1')),
                ('result1', models.CharField(blank=True, max_length=528, null=True, verbose_name='Nəticə/Qiymət ortalaması 1')),
                ('university2', models.CharField(blank=True, max_length=528, null=True, verbose_name='Universitet 2')),
                ('speciality2', models.CharField(blank=True, max_length=528, null=True, verbose_name='İxtisas və dərəcə 2')),
                ('result2', models.CharField(blank=True, max_length=528, null=True, verbose_name='Nəticə/Qiymət ortalaması 2')),
                ('university3', models.CharField(blank=True, max_length=528, null=True, verbose_name='Universitet 3')),
                ('speciality3', models.CharField(blank=True, max_length=528, null=True, verbose_name='İxtisas və dərəcə 3')),
                ('result3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nəticə/Qiymət ortalaması 3')),
                ('start_end_time1', models.CharField(blank=True, max_length=528, null=True, verbose_name='İştirak tarixi: başlanğıc və son tarix 1')),
                ('qualification1', models.CharField(blank=True, max_length=528, null=True, verbose_name='Kvalifikasiya 1')),
                ('place1', models.CharField(blank=True, max_length=528, null=True, verbose_name='Keçirildiyi məkan 1')),
                ('success1', models.CharField(blank=True, max_length=528, null=True, verbose_name='Əldə etdiyi nailiyyət 1')),
                ('start_end_time2', models.CharField(blank=True, max_length=528, null=True, verbose_name='İştirak tarixi: başlanğıc və son tarix 2')),
                ('qualification2', models.CharField(blank=True, max_length=528, null=True, verbose_name='Kvalifikasiya 2')),
                ('place2', models.CharField(blank=True, max_length=528, null=True, verbose_name='Keçirildiyi məkan 2')),
                ('success2', models.CharField(blank=True, max_length=528, null=True, verbose_name='Əldə etdiyi nailiyyət 2')),
                ('start_end_time3', models.CharField(blank=True, max_length=528, null=True, verbose_name='İştirak tarixi: başlanğıc və son tarix 3')),
                ('qualification3', models.CharField(blank=True, max_length=528, null=True, verbose_name='Kvalifikasiya 3')),
                ('place3', models.CharField(blank=True, max_length=528, null=True, verbose_name='Keçirildiyi məkan 3')),
                ('success3', models.CharField(blank=True, max_length=528, null=True, verbose_name='Əldə etdiyi nailiyyət 3')),
                ('other_successes', models.TextField(blank=True, null=True, verbose_name='Digər nailiyyətlər')),
                ('reference_full_name', models.CharField(blank=True, max_length=528, null=True, verbose_name='Soyad, adı, ata adı')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobil nömrə')),
                ('relation', models.CharField(blank=True, max_length=528, null=True, verbose_name='Əlaqə')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVlər',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('image', models.ImageField(upload_to='service_images/', verbose_name='Şəkil')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Məzmun')),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Loqo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/', verbose_name='Ikon')),
                ('about_us', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Haqqımızda')),
                ('about_page_banner', models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Haqqımızda')),
                ('success_page_banner', models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Uğurlarımız')),
                ('service_page_banner', models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Xidmətlərimiz')),
                ('gallery_page_banner', models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Qalereya')),
                ('resume_page_banner', models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='CV göndər')),
                ('contact_page_banner', models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Əlaqə')),
                ('edition_page_banner', models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Nəşrlərimiz')),
                ('register_page_banner', models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Kursa onlayn qeydiyyat')),
            ],
            options={
                'verbose_name': 'Parametr',
                'verbose_name_plural': 'Parametrlər',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('icon_name', models.CharField(max_length=100, verbose_name='İkon')),
                ('color_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rəng kodu')),
            ],
            options={
                'verbose_name': 'Sosial media',
                'verbose_name_plural': 'Sosial media hesabları',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SubscribeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Başlıq')),
            ],
            options={
                'verbose_name': 'Uğur',
                'verbose_name_plural': 'Uğurlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyad')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sahə')),
                ('mission', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vəzifə')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Haqqında')),
            ],
            options={
                'verbose_name': 'Müəllim',
                'verbose_name_plural': 'Müəllimlər',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='VideoGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(max_length=2048, verbose_name='Video linki')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video Qalereya',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SuccessItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(verbose_name='Məzmun')),
                ('success', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_items', to='prestij.successmodel')),
            ],
            options={
                'verbose_name': 'Uğur məzmunu',
                'verbose_name_plural': 'Uğur məzmunları',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PhotoGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=528, verbose_name='Başlıq')),
                ('image', models.ImageField(upload_to='photo_gallery_item_images/', verbose_name='Şəkil')),
                ('photo_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_gallery_items', to='prestij.photogallerymodel')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotolar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BranchContactNumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Əlaqə nömrəsi')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to='prestij.branchmodel')),
            ],
            options={
                'verbose_name': 'Filial əlaqə nömrəsi',
                'verbose_name_plural': 'Filial əlaqə nömrələri',
                'ordering': ('-id',),
            },
        ),
    ]
