# Generated by Django 4.2.3 on 2023-07-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumemodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='resumemodel',
            name='reference_full_name',
        ),
        migrations.RemoveField(
            model_name='resumemodel',
            name='relation',
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobil nömrə 1'),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobil nömrə 2'),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='reference_full_name1',
            field=models.CharField(blank=True, max_length=528, null=True, verbose_name='Soyad, adı, ata adı 1'),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='reference_full_name2',
            field=models.CharField(blank=True, max_length=528, null=True, verbose_name='Soyad, adı, ata adı 2'),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='relation1',
            field=models.CharField(blank=True, max_length=528, null=True, verbose_name='Əlaqə 1'),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='relation2',
            field=models.CharField(blank=True, max_length=528, null=True, verbose_name='Əlaqə 2'),
        ),
    ]
