# Generated by Django 4.2.3 on 2023-07-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0002_remove_resumemodel_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumemodel',
            old_name='start_end_time1',
            new_name='ce_start_end_time1',
        ),
        migrations.RenameField(
            model_name='resumemodel',
            old_name='start_end_time2',
            new_name='ce_start_end_time2',
        ),
        migrations.RenameField(
            model_name='resumemodel',
            old_name='start_end_time3',
            new_name='ce_start_end_time3',
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='ed_start_end_time1',
            field=models.CharField(blank=True, max_length=528, null=True, verbose_name='Təhsil aldığı başlanğıc və son tarix 1'),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='ed_start_end_time2',
            field=models.CharField(blank=True, max_length=528, null=True, verbose_name='Təhsil aldığı başlanğıc və son tarix 2'),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='ed_start_end_time3',
            field=models.CharField(blank=True, max_length=528, null=True, verbose_name='Təhsil aldığı başlanğıc və son tarix 3'),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='work_start_end_time1',
            field=models.CharField(blank=True, max_length=528, null=True, verbose_name='İşlədiyi başlanğıc və son tarixlər 1'),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='work_start_end_time2',
            field=models.CharField(blank=True, max_length=528, null=True, verbose_name='İşlədiyi başlanğıc və son tarixlər 2'),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='work_start_end_time3',
            field=models.CharField(blank=True, max_length=528, null=True, verbose_name='İşlədiyi başlanğıc və son tarixlər 3'),
        ),
    ]
