# Generated by Django 4.2.3 on 2023-07-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0003_rename_start_end_time1_resumemodel_ce_start_end_time1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallerymodel',
            options={'ordering': ('-id',), 'verbose_name': 'Foto Qalereya', 'verbose_name_plural': 'Foto Qalereya'},
        ),
        migrations.AddField(
            model_name='socialmediamodel',
            name='link',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Link'),
        ),
    ]
