# Generated by Django 4.2.3 on 2023-07-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0004_alter_photogallerymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_images/', verbose_name='Şəkil'),
        ),
    ]
