# Generated by Django 4.2.3 on 2023-08-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0005_teachermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='about_page_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='contact_page_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='edition_page_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='gallery_page_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='register_page_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='resume_page_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='service_page_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='success_page_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
    ]
