# Generated by Django 4.2.3 on 2023-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0006_settingsmodel_about_page_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='about_page_active',
            field=models.BooleanField(default=False, verbose_name='Haqqımızda'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='contact_page_active',
            field=models.BooleanField(default=False, verbose_name='Əlaqə'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='edition_page_active',
            field=models.BooleanField(default=False, verbose_name='Nəşrlərimiz'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='gallery_page_active',
            field=models.BooleanField(default=False, verbose_name='Qalereya'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='register_page_active',
            field=models.BooleanField(default=False, verbose_name='Kursa onlayn qeydiyyat'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='resume_page_active',
            field=models.BooleanField(default=False, verbose_name='CV göndər'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='service_page_active',
            field=models.BooleanField(default=False, verbose_name='Xidmətlərimiz'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='success_page_active',
            field=models.BooleanField(default=False, verbose_name='Uğurlarımız'),
        ),
    ]
