# Generated by Django 4.2.3 on 2023-08-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0008_editionmodel_bannermodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='news_page_active',
            field=models.BooleanField(default=True, verbose_name='Xəbərlər'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='news_page_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Xəbərlər'),
        ),
    ]
