# Generated by Django 4.2.3 on 2023-08-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0009_settingsmodel_news_page_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='video_gallery_page_active',
            field=models.BooleanField(default=True, verbose_name='Video Qalereya'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='video_gallery_page_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Video Qalereya'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='gallery_page_active',
            field=models.BooleanField(default=True, verbose_name='Foto Qalereya'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='gallery_page_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='Foto Qalereya'),
        ),
    ]
