# Generated by Django 4.2.3 on 2023-08-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0010_settingsmodel_video_gallery_page_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionmodel',
            name='title',
            field=models.TextField(verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='onlineregister',
            name='school',
            field=models.TextField(verbose_name='Təhsil aldığı məktəb'),
        ),
        migrations.AlterField(
            model_name='onlineregister',
            name='speciality',
            field=models.TextField(verbose_name='İxtisas'),
        ),
        migrations.AlterField(
            model_name='onlineregister',
            name='university',
            field=models.TextField(verbose_name='Bitirdiyi universitet'),
        ),
        migrations.AlterField(
            model_name='photogalleryitem',
            name='title',
            field=models.TextField(max_length=528, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='photogallerymodel',
            name='title',
            field=models.TextField(max_length=528, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='address',
            field=models.TextField(max_length=528, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='birthdate',
            field=models.TextField(max_length=256, verbose_name='Doğum tarixi'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='ce_start_end_time1',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='İştirak tarixi: başlanğıc və son tarix 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='ce_start_end_time2',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='İştirak tarixi: başlanğıc və son tarix 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='ce_start_end_time3',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='İştirak tarixi: başlanğıc və son tarix 3'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='company_name1',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Şirkətin adı, ünvanı və fəaliyyət göstərdiyi sahə 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='company_name2',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Şirkətin adı, ünvanı və fəaliyyət göstərdiyi sahə 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='company_name3',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Şirkətin adı, ünvanı və fəaliyyət göstərdiyi sahə 3'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='duty1',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Vəzifə və əsas öhdəliklər 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='duty2',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Vəzifə və əsas öhdəliklər 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='duty3',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Vəzifə və əsas öhdəliklər 3'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='ed_start_end_time1',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Təhsil aldığı başlanğıc və son tarix 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='ed_start_end_time2',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Təhsil aldığı başlanğıc və son tarix 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='ed_start_end_time3',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Təhsil aldığı başlanğıc və son tarix 3'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='full_name',
            field=models.TextField(max_length=528, verbose_name='Soyad, ad, ata adı'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='home_phone',
            field=models.TextField(max_length=50, verbose_name='Ev telefon nömrəsi'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='leaving_reason1',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Tərk etmə səbəbi 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='leaving_reason2',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Tərk etmə səbəbi 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='leaving_reason3',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Tərk etmə səbəbi 3'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='mobile_phone',
            field=models.TextField(max_length=50, verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='phone_number1',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Mobil nömrə 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='phone_number2',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Mobil nömrə 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='place1',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Keçirildiyi məkan 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='place2',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Keçirildiyi məkan 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='place3',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Keçirildiyi məkan 3'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='qualification1',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Kvalifikasiya 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='qualification2',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Kvalifikasiya 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='qualification3',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Kvalifikasiya 3'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='reference_full_name1',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Soyad, adı, ata adı 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='reference_full_name2',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Soyad, adı, ata adı 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='relation1',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Əlaqə 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='relation2',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Əlaqə 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='result1',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Nəticə/Qiymət ortalaması 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='result2',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Nəticə/Qiymət ortalaması 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='result3',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Nəticə/Qiymət ortalaması 3'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='speciality1',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='İxtisas və dərəcə 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='speciality2',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='İxtisas və dərəcə 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='speciality3',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='İxtisas və dərəcə 3'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='subject',
            field=models.TextField(max_length=528, verbose_name='Tədris etmək istənilən fənn'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='success1',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Əldə etdiyi nailiyyət 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='success2',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Əldə etdiyi nailiyyət 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='success3',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Əldə etdiyi nailiyyət 3'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='university1',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Universitet 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='university2',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Universitet 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='university3',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='Universitet 3'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='vacancy_name',
            field=models.TextField(max_length=528, verbose_name='Müraciət edilən vakansiyanın adı'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='work_start_end_time1',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='İşlədiyi başlanğıc və son tarixlər 1'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='work_start_end_time2',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='İşlədiyi başlanğıc və son tarixlər 2'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='work_start_end_time3',
            field=models.TextField(blank=True, max_length=528, null=True, verbose_name='İşlədiyi başlanğıc və son tarixlər 3'),
        ),
    ]
