# Generated by Django 4.2.3 on 2023-09-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0011_alter_editionmodel_title_alter_onlineregister_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='student_message1',
            field=models.TextField(blank=True, null=True, verbose_name='Ödəniş tarixinə 3 gün qalmış mesaj'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='student_message2',
            field=models.TextField(blank=True, null=True, verbose_name='Ödəniş tarixində mesaj'),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='student_message3',
            field=models.TextField(blank=True, null=True, verbose_name='Ödəniş tarixindən 3 gün sonra mesaj'),
        ),
    ]
