# Generated by Django 4.2.3 on 2023-09-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0012_settingsmodel_student_message1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbiturientOnlineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('school', models.TextField(verbose_name='Təhsil aldığı məktəb')),
                ('identity_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi')),
                ('group', models.CharField(max_length=50, verbose_name='Qrup')),
                ('student_class', models.IntegerField(verbose_name='Sinif')),
                ('dim_point', models.FloatField(verbose_name='Dim balı')),
                ('section', models.CharField(choices=[('AZ', 'Azərbaycan dili'), ('RU', 'Rus dili')], default='AZ', max_length=2, verbose_name='Bölmə')),
                ('status', models.CharField(choices=[('T', 'Tamamlandı'), ('TM', 'Tamamlanmadı')], default='TM', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Abituriyent qeydiyyat',
                'verbose_name_plural': 'Abituriyent qeydiyyatlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AccountingOnlineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('identity_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi')),
                ('status', models.CharField(choices=[('T', 'Tamamlandı'), ('TM', 'Tamamlanmadı')], default='TM', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Mühasibatlıq qeydiyyat',
                'verbose_name_plural': 'Mühasibatlıq qeydiyyatlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CivilServiceOnlineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('university', models.TextField(verbose_name='Bitirdiyi universitet')),
                ('identity_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi')),
                ('status', models.CharField(choices=[('T', 'Tamamlandı'), ('TM', 'Tamamlanmadı')], default='TM', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Dövlət qulluğu qeydiyyat',
                'verbose_name_plural': 'Dövlət qulluğu qeydiyyatlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ComputerCourseOnlineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('identity_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi')),
                ('program_type', models.CharField(max_length=100, verbose_name='Proqram növü')),
                ('status', models.CharField(choices=[('T', 'Tamamlandı'), ('TM', 'Tamamlanmadı')], default='TM', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Kompüter kursu qeydiyyat',
                'verbose_name_plural': 'Kompüter kursu qeydiyyatlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ForeignLanguageOnlineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('identity_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi')),
                ('language', models.CharField(max_length=100, verbose_name='Xarici dil')),
                ('status', models.CharField(choices=[('T', 'Tamamlandı'), ('TM', 'Tamamlanmadı')], default='TM', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Xarici dil qeydiyyat',
                'verbose_name_plural': 'Xarici dillər qeydiyyatlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HighSchoolOnlineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('identity_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi')),
                ('student_class', models.IntegerField(verbose_name='Sinif')),
                ('status', models.CharField(choices=[('T', 'Tamamlandı'), ('TM', 'Tamamlanmadı')], default='TM', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Liseylərə hazırlıq qeydiyyat',
                'verbose_name_plural': 'Liseylərə hazırlıq qeydiyyatlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MasterOnlineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('university', models.TextField(verbose_name='Bitirdiyi universitet')),
                ('speciality', models.TextField(verbose_name='İxtisas')),
                ('identity_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi')),
                ('dim_point', models.FloatField(verbose_name='Qəbul balı')),
                ('language', models.CharField(max_length=100, verbose_name='Xarici dil')),
                ('status', models.CharField(choices=[('T', 'Tamamlandı'), ('TM', 'Tamamlanmadı')], default='TM', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'MIQ qeydiyyat',
                'verbose_name_plural': 'MIQ qeydiyyatlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MIQOnlineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('university', models.TextField(verbose_name='Bitirdiyi universitet')),
                ('speciality', models.TextField(verbose_name='İxtisas')),
                ('identity_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi')),
                ('status', models.CharField(choices=[('T', 'Tamamlandı'), ('TM', 'Tamamlanmadı')], default='TM', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'MIQ qeydiyyat',
                'verbose_name_plural': 'MIQ qeydiyyatlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PreSchoolOnlineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('identity_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi')),
                ('status', models.CharField(choices=[('T', 'Tamamlandı'), ('TM', 'Tamamlanmadı')], default='TM', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Məktəbəqədər hazırlıq qeydiyyat',
                'verbose_name_plural': 'Məktəbəqədər hazırlıq qeydiyyatlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PrimarySchoolOnlineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobil nömrə')),
                ('identity_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi')),
                ('student_class', models.IntegerField(verbose_name='Sinif')),
                ('status', models.CharField(choices=[('T', 'Tamamlandı'), ('TM', 'Tamamlanmadı')], default='TM', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'İbtidai qeydiyyat',
                'verbose_name_plural': 'İbtidai qeydiyyatlar',
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='OnlineRegister',
        ),
    ]
