# Generated by Django 4.2.3 on 2023-09-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestij', '0014_teacheronlineregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturientonlineregister',
            name='full_name',
            field=models.TextField(verbose_name='Ad, soyad'),
        ),
        migrations.AlterField(
            model_name='abiturientonlineregister',
            name='group',
            field=models.TextField(verbose_name='Qrup'),
        ),
        migrations.AlterField(
            model_name='abiturientonlineregister',
            name='identity_card_number',
            field=models.TextField(blank=True, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi'),
        ),
        migrations.AlterField(
            model_name='abiturientonlineregister',
            name='mobile_number',
            field=models.TextField(verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='accountingonlineregister',
            name='full_name',
            field=models.TextField(verbose_name='Ad, soyad'),
        ),
        migrations.AlterField(
            model_name='accountingonlineregister',
            name='identity_card_number',
            field=models.TextField(blank=True, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi'),
        ),
        migrations.AlterField(
            model_name='accountingonlineregister',
            name='mobile_number',
            field=models.TextField(verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='civilserviceonlineregister',
            name='full_name',
            field=models.TextField(verbose_name='Ad, soyad'),
        ),
        migrations.AlterField(
            model_name='civilserviceonlineregister',
            name='identity_card_number',
            field=models.TextField(blank=True, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi'),
        ),
        migrations.AlterField(
            model_name='civilserviceonlineregister',
            name='mobile_number',
            field=models.TextField(verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='computercourseonlineregister',
            name='full_name',
            field=models.TextField(verbose_name='Ad, soyad'),
        ),
        migrations.AlterField(
            model_name='computercourseonlineregister',
            name='identity_card_number',
            field=models.TextField(blank=True, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi'),
        ),
        migrations.AlterField(
            model_name='computercourseonlineregister',
            name='mobile_number',
            field=models.TextField(verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='computercourseonlineregister',
            name='program_type',
            field=models.TextField(verbose_name='Proqram növü'),
        ),
        migrations.AlterField(
            model_name='foreignlanguageonlineregister',
            name='full_name',
            field=models.TextField(verbose_name='Ad, soyad'),
        ),
        migrations.AlterField(
            model_name='foreignlanguageonlineregister',
            name='identity_card_number',
            field=models.TextField(blank=True, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi'),
        ),
        migrations.AlterField(
            model_name='foreignlanguageonlineregister',
            name='language',
            field=models.TextField(verbose_name='Xarici dil'),
        ),
        migrations.AlterField(
            model_name='foreignlanguageonlineregister',
            name='mobile_number',
            field=models.TextField(verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='highschoolonlineregister',
            name='full_name',
            field=models.TextField(verbose_name='Ad, soyad'),
        ),
        migrations.AlterField(
            model_name='highschoolonlineregister',
            name='identity_card_number',
            field=models.TextField(blank=True, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi'),
        ),
        migrations.AlterField(
            model_name='highschoolonlineregister',
            name='mobile_number',
            field=models.TextField(verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='masteronlineregister',
            name='full_name',
            field=models.TextField(verbose_name='Ad, soyad'),
        ),
        migrations.AlterField(
            model_name='masteronlineregister',
            name='identity_card_number',
            field=models.TextField(blank=True, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi'),
        ),
        migrations.AlterField(
            model_name='masteronlineregister',
            name='language',
            field=models.TextField(verbose_name='Xarici dil'),
        ),
        migrations.AlterField(
            model_name='masteronlineregister',
            name='mobile_number',
            field=models.TextField(verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='miqonlineregister',
            name='full_name',
            field=models.TextField(verbose_name='Ad, soyad'),
        ),
        migrations.AlterField(
            model_name='miqonlineregister',
            name='identity_card_number',
            field=models.TextField(blank=True, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi'),
        ),
        migrations.AlterField(
            model_name='miqonlineregister',
            name='mobile_number',
            field=models.TextField(verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='preschoolonlineregister',
            name='full_name',
            field=models.TextField(verbose_name='Ad, soyad'),
        ),
        migrations.AlterField(
            model_name='preschoolonlineregister',
            name='identity_card_number',
            field=models.TextField(blank=True, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi'),
        ),
        migrations.AlterField(
            model_name='preschoolonlineregister',
            name='mobile_number',
            field=models.TextField(verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='primaryschoolonlineregister',
            name='full_name',
            field=models.TextField(verbose_name='Ad, soyad'),
        ),
        migrations.AlterField(
            model_name='primaryschoolonlineregister',
            name='identity_card_number',
            field=models.TextField(blank=True, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi'),
        ),
        migrations.AlterField(
            model_name='primaryschoolonlineregister',
            name='mobile_number',
            field=models.TextField(verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='teacheronlineregister',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teacheronlineregister',
            name='full_name',
            field=models.TextField(verbose_name='Ad, soyad'),
        ),
        migrations.AlterField(
            model_name='teacheronlineregister',
            name='identity_card_number',
            field=models.TextField(blank=True, null=True, verbose_name='Şəxsiyyət vəsiqəsinin nömrəsi'),
        ),
        migrations.AlterField(
            model_name='teacheronlineregister',
            name='mobile_number',
            field=models.TextField(verbose_name='Mobil nömrə'),
        ),
    ]
