# Generated by Django 4.2.3 on 2023-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('status', models.CharField(choices=[('O', 'Oxunub'), ('OM', 'Oxunmayıb')], default='OM', max_length=2, verbose_name='Status')),
                ('type', models.CharField(choices=[('D', 'Silinmə'), ('A', 'Əlavə olunma')], max_length=1, verbose_name='Tip')),
            ],
            options={
                'verbose_name': 'Bildiriş',
                'verbose_name_plural': 'Bildirişlər',
                'ordering': ('-id',),
            },
        ),
    ]
