# Generated by Django 4.2.3 on 2023-09-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='type',
            field=models.CharField(choices=[('D', 'Silinmə'), ('A', 'Əlavə olunma'), ('U', 'Düzəliş')], max_length=1, verbose_name='Əməliyyat'),
        ),
    ]
