from django.urls import path
from prestij.api import views

urlpatterns = [
    path('settings-list/', views.SettingsListAPIView.as_view(), name="settings"),
    path('banners-list/', views.BannerListAPIView.as_view(), name="banners"),
    path('contactinformation-list/', views.ContactInformationListAPIView.as_view(), name="contactinformation-list"),
    path('socialmedia-list/', views.SocialMediaListAPIView.as_view(), name="socialmedia"),
    path('news-list/', views.NewsListAPIView.as_view(), name="news-list"),
    path('news-retrieve/<int:id>/', views.NewsRetrieveAPIView.as_view(), name="news-retrive"),
    path('videogallery-list/', views.VideoGalleryListAPIView.as_view(), name="videogallery-list"),
    path('photogallery-list/', views.PhotoGalleryListAPIView.as_view(), name="photogallery-list"),
    path('photogalleryitem-list/', views.PhotoGalleryItemListAPIView.as_view(), name="photogalleryitem-list"),
    path('teacher-list/', views.TeacherListAPIView.as_view(), name="teacher-list"),
    path('teacher-retrieve/<int:id>/', views.TeacherRetrieveAPIView.as_view(), name="teacher-retrieve"),
    path('service-list/', views.ServiceListAPIView.as_view(), name="service-list"),
    path('service-retrieve/<int:id>/', views.ServiceRetrieveAPIView.as_view(), name="service-retrieve"),
    path('branch-list/', views.BranchListAPIView.as_view(), name="branch-list"),
    path('branchcontactnumber-list/', views.BranchContactNumberListAPIView.as_view(), name="branchcontactnumber-list"),
    path('success-list/', views.SuccessListAPIView.as_view(), name="success-list"),
    path('successitem-list/', views.SuccessItemListAPIView.as_view(), name="successitem-list"),
    path('resume-create/', views.ResumeCreateAPIView.as_view(), name="resume-create"),
    path('contact-create/', views.ContactCreateAPIView.as_view(), name="contact-create"),
    path('teacher-onlineregister-create/', views.TeacherOnlineRegisterCreateAPIView.as_view(), name="teacher-onlineregister-create"),
    path('abiturient-onlineregister-create/', views.AbiturientOnlineRegisterCreateAPIView.as_view(), name="abiturient-onlineregister-create"),
    path('master-onlineregister-create/', views.MasterOnlineRegisterCreateAPIView.as_view(), name="master-onlineregister-create"),
    path('miq-onlineregister-create/', views.MIQOnlineRegisterCreateAPIView.as_view(), name="miq-onlineregister-create"),
    path('civilservice-onlineregister-create/', views.CivilServiceOnlineRegisterCreateAPIView.as_view(), name="civilservice-onlineregister-create"),
    path('computercourse-onlineregister-create/', views.ComputerCourseOnlineRegisterCreateAPIView.as_view(), name="computercourse-onlineregister-create"),
    path('foreignlanguage-onlineregister-create/', views.ForeignLanguageOnlineRegisterCreateAPIView.as_view(), name="foreignlanguage-onlineregister-create"),
    path('accounting-onlineregister-create/', views.AccountingOnlineRegisterCreateAPIView.as_view(), name="accounting-onlineregister-create"),
    path('highschool-onlineregister-create/', views.HighSchoolOnlineRegisterCreateAPIView.as_view(), name="highschool-onlineregister-create"),
    path('preschool-onlineregister-create/', views.PreSchoolOnlineRegisterCreateAPIView.as_view(), name="preschool-onlineregister-create"),
    path('primaryschool-onlineregister-create/', views.PrimarySchoolOnlineRegisterCreateAPIView.as_view(), name="primaryschool-onlineregister-create"),
    path("edition-list/", views.EditionListAPIView.as_view(), name="edition-list"),
    path("edition-retrieve/<int:id>/", views.EditionRetrieveAPIView.as_view(), name="edition-retrieve"),
]