# Generated by Django 4.2.3 on 2023-08-23 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbiturientBlockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Blok',
                'verbose_name_plural': 'Abituriyent blokları',
            },
        ),
        migrations.CreateModel(
            name='AbiturientClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Sinif',
                'verbose_name_plural': 'Abituriyent sinifləri',
            },
        ),
        migrations.CreateModel(
            name='AbiturientGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Qrup',
                'verbose_name_plural': 'Abituriyent qrupları',
            },
        ),
        migrations.CreateModel(
            name='AbiturientSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Fənn',
                'verbose_name_plural': 'Abituriyent fənnləri',
            },
        ),
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
            },
        ),
        migrations.CreateModel(
            name='CivilServiceSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Fənn',
                'verbose_name_plural': 'Dövlət qulluğu fənnləri',
            },
        ),
        migrations.CreateModel(
            name='ComputerProgramTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Proqram növü',
                'verbose_name_plural': 'Kompüter Proqram növləri',
            },
        ),
        migrations.CreateModel(
            name='HighSchoolClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Sinif',
                'verbose_name_plural': 'Liseylərə hazırlıq sinifləri',
            },
        ),
        migrations.CreateModel(
            name='HighSchoolGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Qrup',
                'verbose_name_plural': 'Liseylərə hazırlıq qrupları',
            },
        ),
        migrations.CreateModel(
            name='HighSchoolSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Fənn',
                'verbose_name_plural': 'Liseylərə hazırlıq fənnləri',
            },
        ),
        migrations.CreateModel(
            name='MasterForeignLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Xarici dil',
                'verbose_name_plural': 'Magistr xarici dilləri',
            },
        ),
        migrations.CreateModel(
            name='MasterGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Qrup',
                'verbose_name_plural': 'Magistr qrupları',
            },
        ),
        migrations.CreateModel(
            name='MasterSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Fənn',
                'verbose_name_plural': 'Magistr fənnləri',
            },
        ),
        migrations.CreateModel(
            name='MIQSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Fənn',
                'verbose_name_plural': 'MİQ fənnləri',
            },
        ),
        migrations.CreateModel(
            name='PreSchoolSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Fənn',
                'verbose_name_plural': 'Məktəbəqədər hazırlıq fənnləri',
            },
        ),
        migrations.CreateModel(
            name='PrimarySchoolClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Sinif',
                'verbose_name_plural': 'İbtidai sinifləri',
            },
        ),
        migrations.CreateModel(
            name='PrimarySchoolGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Qrup',
                'verbose_name_plural': 'İbtidai qrupları',
            },
        ),
        migrations.CreateModel(
            name='PrimarySchoolSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Fənn',
                'verbose_name_plural': 'İbtidai fənnləri',
            },
        ),
        migrations.CreateModel(
            name='SeasonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlama tarixi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitmə tarixi')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='service.branchmodel', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Sezon',
                'verbose_name_plural': 'Sezonlar',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('specialty', models.CharField(blank=True, max_length=300, null=True, verbose_name='İxtisas')),
                ('section', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bölmə')),
                ('salary', models.FloatField(blank=True, null=True, verbose_name='Aylıq əmək haqqı')),
                ('phone_number1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon nömrəsi')),
                ('wp_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Whatsapp nömrəsi')),
                ('status', models.CharField(choices=[('QE', 'Qeyd edilməyib'), ('TS', 'Tələbə sayı'), ('FM', 'Fiks maaş')], default='QE', max_length=2, verbose_name='Status')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='service.seasonmodel', verbose_name='Sezon')),
            ],
            options={
                'verbose_name': 'Müəllim',
                'verbose_name_plural': 'Müəllimlər',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('phone_number1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon nömrəsi 1')),
                ('phone_number2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon nömrəsi 2')),
                ('wp_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Whatsapp nömrəsi')),
                ('status', models.CharField(choices=[('DE', 'Davam edir'), ('D', 'Dondurulub'), ('B', 'Bitirilib')], default='DE', max_length=2, verbose_name='Status')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='service.seasonmodel', verbose_name='Sezon')),
            ],
            options={
                'verbose_name': 'Tələbə',
                'verbose_name_plural': 'Tələbələr',
            },
        ),
        migrations.CreateModel(
            name='PrimarySchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_primaryschools', to='service.highschoolgroupmodel', verbose_name='Qrup')),
                ('primaryschool_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_primaryschools', to='service.highschoolclassmodel', verbose_name='Sinif')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primaryschool', to='service.studentmodel', verbose_name='Tələbə')),
                ('subjects', models.ManyToManyField(related_name='subject_primaryschools', to='service.highschoolsubjectmodel', verbose_name='Fənnlər')),
            ],
            options={
                'verbose_name': 'İbtidai',
                'verbose_name_plural': 'İbtidailər',
            },
        ),
        migrations.CreateModel(
            name='PreSchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preschool', to='service.studentmodel', verbose_name='Tələbə')),
                ('subjects', models.ManyToManyField(related_name='subject_preschools', to='service.preschoolsubjectmodel', verbose_name='Fənnlər')),
            ],
            options={
                'verbose_name': 'Məktəbəqədər hazırlıq',
                'verbose_name_plural': 'Məktəbəqədər hazırlıqlar',
            },
        ),
        migrations.CreateModel(
            name='MIQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=300, verbose_name='İxtisas')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='miq', to='service.studentmodel', verbose_name='Tələbə')),
                ('subjects', models.ManyToManyField(related_name='subject_miqs', to='service.miqsubjectmodel', verbose_name='Fənnlər')),
            ],
            options={
                'verbose_name': 'MİQ',
                'verbose_name_plural': 'MİQlər',
            },
        ),
        migrations.CreateModel(
            name='MasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_point', models.FloatField(blank=True, null=True, verbose_name='Ali məktəbə qəbul balı')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_masters', to='service.mastergroupmodel', verbose_name='Qrup')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_masters', to='service.masterforeignlanguagemodel', verbose_name='Xarici dil')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='service.studentmodel', verbose_name='Tələbə')),
                ('subjects', models.ManyToManyField(related_name='subject_masters', to='service.mastersubjectmodel', verbose_name='Fənnlər')),
            ],
            options={
                'verbose_name': 'Magistrant',
                'verbose_name_plural': 'Magistrantlar',
            },
        ),
        migrations.CreateModel(
            name='HighSchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_highschools', to='service.highschoolgroupmodel', verbose_name='Qrup')),
                ('highschool_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_highschools', to='service.highschoolclassmodel', verbose_name='Sinif')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highschool', to='service.studentmodel', verbose_name='Tələbə')),
                ('subjects', models.ManyToManyField(related_name='subject_highschools', to='service.highschoolsubjectmodel', verbose_name='Fənnlər')),
            ],
            options={
                'verbose_name': 'Liseylərə hazırlıq',
                'verbose_name_plural': 'Liseylərə hazırlıqlar',
            },
        ),
        migrations.CreateModel(
            name='ForeignLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foreignlanguage', to='service.studentmodel', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Xarici dil',
                'verbose_name_plural': 'Xarici dillər',
            },
        ),
        migrations.CreateModel(
            name='ComputerCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_types', models.ManyToManyField(related_name='programtypes_computercourses', to='service.computerprogramtypemodel', verbose_name='Proqram növləri')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computercourse', to='service.studentmodel', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Komputer kursu',
                'verbose_name_plural': 'Komputer kursları',
            },
        ),
        migrations.CreateModel(
            name='CivilServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='civilservice', to='service.studentmodel', verbose_name='Tələbə')),
                ('subjects', models.ManyToManyField(related_name='subject_civilservices', to='service.civilservicesubjectmodel', verbose_name='Fənnlər')),
            ],
            options={
                'verbose_name': 'Dövlət qulluğu',
                'verbose_name_plural': 'Dövlət qulluqları',
            },
        ),
        migrations.CreateModel(
            name='AccountingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting', to='service.studentmodel', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Mühasibatlıq',
                'verbose_name_plural': 'Mühasibatlıqlar',
            },
        ),
        migrations.CreateModel(
            name='AccountantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accountant', to='service.branchmodel')),
            ],
            options={
                'verbose_name': 'Mühasib',
                'verbose_name_plural': 'Mühasiblər',
            },
        ),
        migrations.CreateModel(
            name='AbiturientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_point', models.FloatField(blank=True, null=True, verbose_name='DİM balı')),
                ('abiturient_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_abiturients', to='service.abiturientclassmodel', verbose_name='Sinif')),
                ('blocks', models.ManyToManyField(related_name='block_abiturients', to='service.abiturientblockmodel', verbose_name='Bloklar')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_abiturients', to='service.abiturientgroupmodel', verbose_name='Qrup')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abiturient', to='service.studentmodel', verbose_name='Tələbə')),
                ('subjects', models.ManyToManyField(related_name='subject_abiturients', to='service.abiturientsubjectmodel', verbose_name='Fənnlər')),
            ],
            options={
                'verbose_name': 'Abituriyent',
                'verbose_name_plural': 'Abituriyentlər',
            },
        ),
    ]
