# Generated by Django 4.2.3 on 2023-08-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryschoolmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_primaryschools', to='service.primaryschoolgroupmodel', verbose_name='Qrup'),
        ),
        migrations.AlterField(
            model_name='primaryschoolmodel',
            name='primaryschool_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_primaryschools', to='service.primaryschoolclassmodel', verbose_name='Sinif'),
        ),
        migrations.AlterField(
            model_name='primaryschoolmodel',
            name='subjects',
            field=models.ManyToManyField(related_name='subject_primaryschools', to='service.primaryschoolsubjectmodel', verbose_name='Fənnlər'),
        ),
    ]
