# Generated by Django 4.2.3 on 2023-08-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_primaryschoolmodel_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturientmodel',
            name='abiturient_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_abiturients', to='service.abiturientclassmodel', verbose_name='Sinif'),
        ),
        migrations.AlterField(
            model_name='abiturientmodel',
            name='blocks',
            field=models.ManyToManyField(blank=True, null=True, related_name='block_abiturients', to='service.abiturientblockmodel', verbose_name='Bloklar'),
        ),
        migrations.AlterField(
            model_name='abiturientmodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_abiturients', to='service.abiturientgroupmodel', verbose_name='Qrup'),
        ),
        migrations.AlterField(
            model_name='abiturientmodel',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='subject_abiturients', to='service.abiturientsubjectmodel', verbose_name='Fənnlər'),
        ),
    ]
