# Generated by Django 4.2.3 on 2023-08-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_abiturientmodel_abiturient_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiturientmodel',
            name='sector',
            field=models.CharField(choices=[('AZ', 'Azərbaycan dili'), ('RU', 'Rus dili')], default='AZ', max_length=2, verbose_name='Bölmə'),
        ),
    ]
