# Generated by Django 4.2.3 on 2023-09-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_abiturientmodel_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterforeignlanguagemodel',
            options={'verbose_name': 'Xarici dil', 'verbose_name_plural': 'Magistratura xarici dilləri'},
        ),
        migrations.AlterModelOptions(
            name='mastergroupmodel',
            options={'verbose_name': 'Qrup', 'verbose_name_plural': 'Magistraturaya hazırlıq qrupları'},
        ),
        migrations.AlterModelOptions(
            name='mastermodel',
            options={'verbose_name': 'Magistraturaya hazırlıq', 'verbose_name_plural': 'Magistraturaya hazırlıqlar'},
        ),
        migrations.AlterModelOptions(
            name='mastersubjectmodel',
            options={'verbose_name': 'Fənn', 'verbose_name_plural': 'Magistraturaya hazırlıq fənnləri'},
        ),
    ]
