# Generated by Django 4.2.3 on 2023-10-05 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='service.seasonmodel', verbose_name='Sezon')),
            ],
            options={
                'verbose_name': 'Ay',
                'verbose_name_plural': 'Aylar',
            },
        ),
        migrations.CreateModel(
            name='TeacherPaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payments', to='service.teachermodel', verbose_name='Müəllim')),
            ],
            options={
                'verbose_name': 'Müəllim ödəniş məlumatı',
                'verbose_name_plural': 'Müəllim ödəniş məlumatları',
            },
        ),
        migrations.CreateModel(
            name='PrimarySchoolPaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prs_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
                ('primaryschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_payments', to='service.primaryschoolmodel', verbose_name='İbtidai')),
            ],
            options={
                'verbose_name': 'İbtidai ödəniş məlumatı',
                'verbose_name_plural': 'İbtidai ödəniş məlumatları',
            },
        ),
        migrations.CreateModel(
            name='PreSchoolPaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
                ('preschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preschool_payments', to='service.preschoolmodel', verbose_name='Məktəbəqədər hazırlıq')),
            ],
            options={
                'verbose_name': 'Məktəbəqədər hazırlıq ödəniş məlumatı',
                'verbose_name_plural': 'Məktəbəqədər hazırlıq ödəniş məlumatları',
            },
        ),
        migrations.CreateModel(
            name='MIQPaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('miq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miq_payments', to='service.miqmodel', verbose_name='MİQ')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
            ],
            options={
                'verbose_name': 'MİQ ödəniş məlumatı',
                'verbose_name_plural': 'MİQ ödəniş məlumatları',
            },
        ),
        migrations.CreateModel(
            name='MasterPaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_payments', to='service.mastermodel', verbose_name='Magistrant')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
            ],
            options={
                'verbose_name': 'Magistraturaya hazırlıq ödəniş məlumatı',
                'verbose_name_plural': 'Magistraturaya hazırlıq ödəniş məlumatları',
            },
        ),
        migrations.CreateModel(
            name='HighSchoolPaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highschool_payments', to='service.highschoolmodel', verbose_name='Liseylərə hazırlıq')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
            ],
            options={
                'verbose_name': 'Liseylərə hazırlıq ödəniş məlumatı',
                'verbose_name_plural': 'Liseylərə hazırlıq ödəniş məlumatları',
            },
        ),
        migrations.CreateModel(
            name='ForeignLanguagePaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('foreignlanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreignlanguage_payments', to='service.foreignlanguagemodel', verbose_name='Xarici dil')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fl_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
            ],
            options={
                'verbose_name': 'Xarici dil ödəniş məlumatı',
                'verbose_name_plural': 'Xarici dil ödəniş məlumatları',
            },
        ),
        migrations.CreateModel(
            name='ComputerCoursePaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('computercourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computercourse_payments', to='service.computercoursemodel', verbose_name='Komputer kursu')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
            ],
            options={
                'verbose_name': 'Komputer kursu ödəniş məlumatı',
                'verbose_name_plural': 'Komputer kursu ödəniş məlumatları',
            },
        ),
        migrations.CreateModel(
            name='CivilServicePaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('civilservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civilservice_payments', to='service.civilservicemodel', verbose_name='Dövləq qulluğu')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cs_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
            ],
            options={
                'verbose_name': 'Dövlət qulluğu ödəniş məlumatı',
                'verbose_name_plural': 'Dövlət qulluğu ödəniş məlumatları',
            },
        ),
        migrations.CreateModel(
            name='AccountingPaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('accounting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_payments', to='service.accountingmodel', verbose_name='Mühasibatlıq')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
            ],
            options={
                'verbose_name': 'Mühasibatlıq ödəniş məlumatı',
                'verbose_name_plural': 'Mühasibatlıq ödəniş məlumatları',
            },
        ),
        migrations.CreateModel(
            name='AbiturientPaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('abiturient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abiturient_payments', to='service.abiturientmodel', verbose_name='Abituriyent')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
            ],
            options={
                'verbose_name': 'Abituriyent ödəniş məlumatı',
                'verbose_name_plural': 'Abituriyent ödəniş məlumatları',
            },
        ),
    ]
