# Generated by Django 4.2.3 on 2023-10-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_studentmodel_language_and_more'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_payments', to='accounting.monthmodel', verbose_name='Ay')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stduent_payments', to='service.studentmodel', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Tələbə ödəniş məlumatı',
                'verbose_name_plural': 'Tələbə ödəniş məlumatları',
            },
        ),
    ]
