# Generated by Django 4.2.3 on 2023-10-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_studentpaymentinformationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingpaymentinformationmodel',
            name='accounting',
        ),
        migrations.RemoveField(
            model_name='accountingpaymentinformationmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='civilservicepaymentinformationmodel',
            name='civilservice',
        ),
        migrations.RemoveField(
            model_name='civilservicepaymentinformationmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='computercoursepaymentinformationmodel',
            name='computercourse',
        ),
        migrations.RemoveField(
            model_name='computercoursepaymentinformationmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='foreignlanguagepaymentinformationmodel',
            name='foreignlanguage',
        ),
        migrations.RemoveField(
            model_name='foreignlanguagepaymentinformationmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='highschoolpaymentinformationmodel',
            name='highschool',
        ),
        migrations.RemoveField(
            model_name='highschoolpaymentinformationmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='masterpaymentinformationmodel',
            name='master',
        ),
        migrations.RemoveField(
            model_name='masterpaymentinformationmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='miqpaymentinformationmodel',
            name='miq',
        ),
        migrations.RemoveField(
            model_name='miqpaymentinformationmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='preschoolpaymentinformationmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='preschoolpaymentinformationmodel',
            name='preschool',
        ),
        migrations.RemoveField(
            model_name='primaryschoolpaymentinformationmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='primaryschoolpaymentinformationmodel',
            name='primaryschool',
        ),
        migrations.DeleteModel(
            name='AbiturientPaymentInformationModel',
        ),
        migrations.DeleteModel(
            name='AccountingPaymentInformationModel',
        ),
        migrations.DeleteModel(
            name='CivilServicePaymentInformationModel',
        ),
        migrations.DeleteModel(
            name='ComputerCoursePaymentInformationModel',
        ),
        migrations.DeleteModel(
            name='ForeignLanguagePaymentInformationModel',
        ),
        migrations.DeleteModel(
            name='HighSchoolPaymentInformationModel',
        ),
        migrations.DeleteModel(
            name='MasterPaymentInformationModel',
        ),
        migrations.DeleteModel(
            name='MIQPaymentInformationModel',
        ),
        migrations.DeleteModel(
            name='PreSchoolPaymentInformationModel',
        ),
        migrations.DeleteModel(
            name='PrimarySchoolPaymentInformationModel',
        ),
    ]
