# Generated by Django 4.2.3 on 2023-08-26 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_abiturientmodel_sector'),
        ('accounting', '0002_abiturientpaymentinformationmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturientpaymentinformationmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ödənişin statusu'),
        ),
        migrations.AlterField(
            model_name='accountingpaymentinformationmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ödənişin statusu'),
        ),
        migrations.AlterField(
            model_name='civilservicepaymentinformationmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ödənişin statusu'),
        ),
        migrations.AlterField(
            model_name='computercoursepaymentinformationmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ödənişin statusu'),
        ),
        migrations.AlterField(
            model_name='foreignlanguagepaymentinformationmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ödənişin statusu'),
        ),
        migrations.AlterField(
            model_name='highschoolpaymentinformationmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ödənişin statusu'),
        ),
        migrations.AlterField(
            model_name='masterpaymentinformationmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ödənişin statusu'),
        ),
        migrations.AlterField(
            model_name='miqpaymentinformationmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ödənişin statusu'),
        ),
        migrations.AlterField(
            model_name='preschoolpaymentinformationmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ödənişin statusu'),
        ),
        migrations.AlterField(
            model_name='primaryschoolpaymentinformationmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ödənişin statusu'),
        ),
        migrations.CreateModel(
            name='TeacherPaymentInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödənişin tarixi')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Ödəniş məbləği')),
                ('status', models.BooleanField(default=False, verbose_name='Ödənişin statusu')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_month_payments', to='accounting.monthmodel', verbose_name='Ay')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payments', to='service.teachermodel', verbose_name='Müəllim')),
            ],
            options={
                'verbose_name': 'Müəllim ödəniş məlumatı',
                'verbose_name_plural': 'Müəllim ödəniş məlumatları',
            },
        ),
    ]
