# Generated by Django 4.2.3 on 2023-09-06 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_abiturientpaymentinformationmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterpaymentinformationmodel',
            options={'verbose_name': 'Magistraturaya hazırlıq ödəniş məlumatı', 'verbose_name_plural': 'Magistraturaya hazırlıq ödəniş məlumatları'},
        ),
    ]
