# Generated by Django 4.2.3 on 2023-10-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_accountingpaymentinformationmodel_accounting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymentinformationmodel',
            name='payment_type',
            field=models.CharField(choices=[('N', 'Nağd'), ('HK', 'Hesaba köçürmə')], default='N', max_length=2, verbose_name='Ödənişin növü'),
        ),
        migrations.AddField(
            model_name='teacherpaymentinformationmodel',
            name='payment_type',
            field=models.CharField(choices=[('N', 'Nağd'), ('HK', 'Hesaba köçürmə')], default='N', max_length=2, verbose_name='Ödənişin növü'),
        ),
    ]
